sudo: required
language: csharp
dist: xenial
dotnet: 5.0
mono: none
services:
  - docker

stages:
  - compile & unit test
  - test

env:
  - CONFIGURATION=Release NOTHREADS=30 SECURITY=OFF
  - CONFIGURATION=Release NOTHREADS=30 SECURITY=SSL
  - CONFIGURATION=Release NOTHREADS=30 SECURITY=TLS
  - CONFIGURATION=Release NOTHREADS=20 SECURITY=OFF
  - CONFIGURATION=Release NOTHREADS=20 SECURITY=SSL
  - CONFIGURATION=Release NOTHREADS=20 SECURITY=TLS
  - CONFIGURATION=Release NOTHREADS=10 SECURITY=OFF
  - CONFIGURATION=Release NOTHREADS=10 SECURITY=SSL
  - CONFIGURATION=Release NOTHREADS=10 SECURITY=TLS

addons:
  apt:
    packages:
    - ldap-utils
    - gnutls-bin
    - ssl-cert
    - slapd
    - dotnet-sdk-3.1

before_script:
  - chmod ugo+x configure-opendj.sh
  - chmod ugo+x configure-openldap.sh
  - ./configure-opendj.sh
  - ./configure-openldap.sh

jobs:
  include:
    - stage: compile & unit test
      env:
      - CONFIGURATION=Release
      script:
      - dotnet restore
      - dotnet build --configuration $CONFIGURATION
      - export TRANSPORT_SECURITY=OFF; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj -f net5
      - export TRANSPORT_SECURITY=OFF; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj -f netcoreapp3.1
      - export TRANSPORT_SECURITY=SSL; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj -f net5
      - export TRANSPORT_SECURITY=SSL; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj -f netcoreapp3.1
      - export TRANSPORT_SECURITY=TLS; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj -f net5
      - export TRANSPORT_SECURITY=TLS; dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj -f netcoreapp3.1
      - dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.UnitTests/Novell.Directory.Ldap.NETStandard.UnitTests.csproj -f net5
      - dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.UnitTests/Novell.Directory.Ldap.NETStandard.UnitTests.csproj -f netcoreapp3.1

script:
  - dotnet restore
  - dotnet build --configuration $CONFIGURATION
  - export TRANSPORT_SECURITY=$SECURITY; dotnet run --configuration $CONFIGURATION --project test/Novell.Directory.Ldap.NETStandard.StressTests/Novell.Directory.Ldap.NETStandard.StressTests.csproj $NOTHREADS 30